# OrangeHRM Demo Portal — opensource-demo.orangehrmlive.com
base.url=https://opensource-demo.orangehrmlive.com
api.base.url=https://gorest.co.in

credentials.username=Admin
credentials.password=admin123
