# SauceDemo E-commerce Portal — www.saucedemo.com
base.url=https://www.saucedemo.com
api.base.url=https://fakestoreapi.com

credentials.username=standard_user
credentials.password=secret_sauce

# Additional test accounts
credentials.locked.username=locked_out_user
credentials.problem.username=problem_user
